### ISSUE TITLE
Retrieve Sensor Data

### ISSUE THREAD

**Issue by jmaugerdumais** [NorthernMan54/homebridge-HTTP-IRBlaster#2]
Hello !
Nice plugin ! I'm using it to control my fireplace :) 

2 questions : 

1) Is there a way to retrieve sensors data from this plugin with a DHT22 ? 

2) Would it be a way to have some kind of stateless switch to increase/decrease the Fireplace flame instead of a fan ? The % method (like a fan) to increase/decrease is not ultra responsive in Homekit...

Thanks a lot in advance !

**Comment by NorthernMan54** [comment]
Thanks for the feedback on the plugin

1 - I have thought about adding a local temperature sensor to the ESP8266 Code, but as they are very cheap, you could just run a second ESP8266 in the room to monitor the fireplace temperature.   With mine, I have a RPI running Kodi in the same room, with a BME280 and homebridge running to monitor temperature.

Also, if you use the Elgato Eve app, you can setup an automation to turn the fireplace if it gets too warm ;-)

2 - I agree on the dimmer control in HomeKit as being terrible.  In my setup I use an Alexa to control it.  So I just call out to Alexa, turn fireplace to 50.   With the Alexa integration I hit a 100% on the WAF score on this one.

Do you have the same remote as I do or ???

**Comment by jmaugerdumais** [comment]
Hello !
I have almost the same remote. Same frequency, and the end of the FCC ID is slightly different but the code (for the end part) is the same. 

On my side I’m not an Alexa user, I rely only on Homekit, which is why I was wondering if the plugin could be detected as a stateless switch instead. 

Also, except on/off/up/down, is there other input type possible ? Could it be possible to add some others ? 

Thanks !

Julien

**Comment by jmaugerdumais** [comment]
Oh ! And about the sensor, let say that I wanted to maintain something as integrated as possible, is there something that could be done easily or absolutely not ?

**Comment by jmaugerdumais** [comment]
Me again ... a bit off this topic but also I’m having an issue where the accessory fireplace is always going in “no answer” in homekit. Any idea ?

**Comment by NorthernMan54** [comment]
@jmaugerdumais The reason I mentioned Alexa, is I also integrated HomeBridge to Alexa, so for the other users in the house, they now mostly use Alexa and rarely use the Home App or Siri.  You could with Siri, just say "Hey Siri, turn fireplace to 50".

For changing the plugin to work differently, I like using the Fan model, as it has on/off and and the slider for variable control.  How would it work with buttons?  If your using HomeKit, could you do a scene and achieve what your looking for?

Regarding adding a sensor to this, as I don't own the code on ESP8266 I really can't say.

Regarding "no answer", sounds like network or wifi issues in your location.  Mine is very solid, no issues

**Comment by jmaugerdumais** [comment]
Hello !
When I’m asking Siri to turn the fireplace to 50 (or any other measure) the blaster is only sending one command to the blaster and the fireplace will increase by only one notch. 

As for the button idea, here’s what I was thinking :

Let say that I create a room named fireplace, each button (stateless button type) would be sending a command. Keeping it pressed in Home would continuously sending the command. 

But for it to work, it would be necessary to have one button per command ... unless there is another accessory type in Home that could be used. 

Does on your home app (on your side) the accessory Fireplace remember the last percentage state or it always return to 0% ? 

Thanks !

**Comment by NorthernMan54** [comment]
In the plugin, it has 3 mode's of operation depending on the configuration.

Includes on_data and up_data - Configures as fan
Includes on_data - configures as a switch, and sends on_data or off_data
Doesn't include on_data - configures as a stateless switch and only uses the URL option.

Using an accessory with just on/off data you should be able to get close to what you are describing.

The home app / homebridge does remember state.  It is stored within homebridge, but if it restarts the state is lost.  For me it remembers the percentage for days.

**Comment by NorthernMan54** [comment]
I was just using mine via Siri, for the first time, and it wasn't that bad.  I said 'turn on fireplace', then about a minute later I said 'turn fireplace to 50', and it worked fine.

**Comment by jmaugerdumais** [comment]
Found the issue : I had to put the step to 100 instead of 10. Now it does send the command correctly !

Many thanks to the support ! :)

**Comment by NorthernMan54** [comment]
Awesome
